# Generated by Django 3.2.2 on 2021-05-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('device_type', models.CharField(max_length=30)),
                ('api_key', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
        ),
    ]
