# Generated by Django 3.2.2 on 2021-05-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0004_door_location'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='door',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Door', to='door.door'),
        ),
    ]
