# Generated by Django 3.2.2 on 2021-05-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('suite_number', models.CharField(max_length=255)),
                ('version', models.IntegerField()),
            ],
        ),
    ]
