# Generated by Django 3.2.2 on 2021-05-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
