# Generated by Django 3.2.2 on 2021-05-09 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('suite', '0002_alter_suite_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='suite',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Location_Suite', to='location.location'),
        ),
    ]
