# Generated by Django 3.2.2 on 2021-05-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0008_alter_door_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='message',
        ),
    ]
