# Generated by Django 3.2.2 on 2021-05-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
